# Configuração do Pipeline de Dados
# config/pipeline-config.yaml

# Configurações gerais
project:
  name: "kpis-dashboard"
  version: "1.0.0"
  description: "Pipeline de dados para KPIs estratégicos"
  
# Configurações de infraestrutura
infrastructure:
  cloud_provider: "aws"  # aws, azure, gcp
  region: "us-east-1"
  
  # Data Warehouse
  warehouse:
    type: "snowflake"
    account: "company.snowflakecomputing.com"
    database: "ANALYTICS"
    warehouse: "COMPUTE_WH"
    schema: "MARTS"
    
  # Object Storage
  storage:
    type: "s3"
    bucket: "company-data-lake"
    prefix: "raw-data/"
    
# Configurações de conectores
connectors:
  airbyte:
    url: "http://airbyte-server:8001"
    connections:
      - name: "ploomes-crm"
        source: "source-ploomes"
        destination: "destination-snowflake"
        schedule: "0 */30 * * * *"  # A cada 30 minutos
        sync_mode: "incremental"
        
      - name: "sap-b1"
        source: "source-sap-b1"
        destination: "destination-snowflake"
        schedule: "0 0 * * * *"  # A cada hora
        sync_mode: "incremental"
        
      - name: "whatsapp-api"
        source: "source-whatsapp"
        destination: "destination-snowflake"
        schedule: "0 */5 * * * *"  # A cada 5 minutos
        sync_mode: "incremental"

# Configurações do dbt
dbt:
  profiles_dir: "/opt/airflow/dbt/profiles"
  project_dir: "/opt/airflow/dbt"
  target: "prod"
  
  models:
    materialization: "table"
    
    staging:
      materialized: "view"
      
    marts:
      materialized: "table"
      
    kpis:
      materialized: "table"
      cluster_by: ["date_key"]
      
# Configurações de qualidade
quality:
  great_expectations:
    config_path: "/opt/airflow/great_expectations"
    
    suites:
      - name: "raw_data_suite"
        tables: ["raw_ploomes_leads", "raw_sap_orders"]
        
      - name: "kpis_suite"
        tables: ["fct_kpis_commercial", "fct_kpis_operational", "fct_kpis_financial"]
        
    tests:
      - expectation_type: "expect_column_values_to_not_be_null"
        column: "id"
        
      - expectation_type: "expect_column_values_to_be_between"
        column: "conversion_rate"
        min_value: 0
        max_value: 100

# Configurações de monitoramento
monitoring:
  grafana:
    url: "http://grafana:3000"
    
  prometheus:
    url: "http://prometheus:9090"
    
  alerts:
    slack:
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#data-alerts"
      
    email:
      smtp_server: "smtp.company.com"
      recipients: ["data-team@company.com"]

# Configurações de segurança
security:
  encryption:
    at_rest: true
    in_transit: true
    
  access_control:
    rbac: true
    
  data_classification:
    levels: ["public", "internal", "confidential", "restricted"]
    
  retention:
    transactional_data: "7 years"
    marketing_data: "3 years"
    logs: "1 year"
    personal_data: "2 years"

# Configurações de performance
performance:
  caching:
    enabled: true
    ttl: 3600  # 1 hour
    
  partitioning:
    enabled: true
    column: "date_key"
    
  clustering:
    enabled: true
    columns: ["date_key", "channel"]

# Configurações de backup
backup:
  enabled: true
  frequency: "daily"
  retention: "30 days"
  storage: "s3://company-backups/data-warehouse/"

# Configurações de ambiente
environments:
  development:
    database: "DEV_ANALYTICS"
    warehouse: "DEV_COMPUTE_WH"
    
  staging:
    database: "STAGING_ANALYTICS"
    warehouse: "STAGING_COMPUTE_WH"
    
  production:
    database: "PROD_ANALYTICS"
    warehouse: "PROD_COMPUTE_WH"

# Configurações de SLA
sla:
  data_freshness:
    ploomes: 30  # minutes
    sap_b1: 60   # minutes
    whatsapp: 15 # minutes
    
  pipeline_execution:
    etl: 120     # minutes
    dbt: 60      # minutes
    tests: 30    # minutes
    
  dashboard_refresh:
    power_bi: 30 # minutes
    
# Configurações de notificações
notifications:
  pipeline_success:
    enabled: false
    
  pipeline_failure:
    enabled: true
    severity: "critical"
    
  data_quality_failure:
    enabled: true
    severity: "warning"
    
  sla_breach:
    enabled: true
    severity: "warning"
